### ISSUE TITLE
BonDriverの設定

### ISSUE THREAD

**Issue by JohnDoe-001** [xtne6f/TTRec#1]
設定の「使用するBonDriver」で地デジ用と衛星放送用のBonDriverを設定できるようにして、
録画予約時に実際に使用するBonDriverを自動選択できるようにできないでしょうか？

**Comment by xtne6f** [comment]
まずは、TTRec_Readme.txt の「複数チューナでの使用」は読まれましたでしょうか？
TTRecはプラグイン1つにつきチューナ1つを固定するのが基本思想なので
ここを軸足に問題点など要望して頂ければと思います。

**Comment by JohnDoe-001** [comment]
「複数チューナでの使用」は読んで説明どおりに設定つもりです
しかしこの方法ですと地デジを受信状態で起動した場合、CSの番組を予約するときにわざわざプラグインを切り替えなければなりません（設定方法が間違っているのでしょうか？）
このプラグインを視聴予約用として使用しており、「地デジ→CS→地デジ」といった予約をしたい場合がよくありとても面倒です
なのでこの機能をリクエストしました

**Comment by xtne6f** [comment]
とりわけ視聴予約に対して確かに便利に感じたので、おおむね要望の機能を追加しました。

**Comment by JohnDoe-001** [comment]
今更ですが、対応していただきありがとうございました
