### ISSUE TITLE
TVTESTプラグインリスト名

### ISSUE THREAD

**Issue by Filicya** [xtne6f/TTRec#2]
複数録画する際にTTRecのみ複数ならんで何用に設定しているかわかりずらいので、
TTRec(bonドライバ名)等と表示されるようにできませんでしょうか？
忙しいでしょうが考慮おねがいします。

**Comment by xtne6f** [comment]
どの部分についてかちょっと判断つきませんが
プラグインファイル名が`TTRec.tvtp`でない場合はタイトルバーなどに括弧書きされるので
基本的にはプラグインファイル名を分かりやすい名前にしてもらえればと思います。

![titlebar](https://user-images.githubusercontent.com/2673799/190948452-8c868771-dfde-4ef3-9a09-02d92b76193c.png)

**Comment by xtne6f** [comment]
あっ、TVTest画面の右クリックからのプラグインの有効状態を示すメニューでしょうか
ここの名前、できなくはないですが変更するのはちょっと微妙かなと思います。
(個別の名前というよりプラグインそのものの種類というか名前の部分なので…)

**Comment by Filicya** [comment]
そうです。TVTest画面の右クリックからのプラグインの有効状態を示すメニューの事ですね。
設定がちゃんと合ってるかどうか、Tvtestの地上派とBSでini分けて起動してるんですが、
同じ名前にチェックがついてるとわかりずらいので、名前がせめて違ったらわかりやすいなと...

**Comment by xtne6f** [comment]
起動したTVTestがどのTTRecのものか（どのTTRecが有効になっているか）については
「TTRec状態」のステータスバーを置いて区別する方法があります。

![status](https://user-images.githubusercontent.com/2673799/191227343-e9b7cc5f-59e2-40c6-be15-a19ae8f11914.jpg)

有効状態を示すメニューのところは非固定の文字列にすると本体や他プラグインに迷惑かかる可能性 (プラグインがTTRecかどうか識別できなくなる) がちょっと気になるので、現状維持しようと思います。

**Comment by Filicya** [comment]
機能紹介ありがとうございます。
Ver古いのか設定画面でないので、新しいTvtestをビルドしてみます。
ありがとうございました。

**Comment by Filicya** [comment]
機能紹介ありがとうございます。
Ver古いのか設定画面でないので、新しいTvtestをビルドしてみます。
ありがとうございました。
